pipeline {
    agent any

    environment {
        IMAGE_NAME = 'venkataramireddy1999/flask-jenkins-docker'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/venkataramireddy1999/jenkins-projects.git'
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    passwordVariable: 'DOCKER_PASSWORD',
                    usernameVariable: 'DOCKER_USERNAME'
                )]) {
                    bat """
                        echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('02-jenkins-docker') {
                    bat 'docker build -t %IMAGE_NAME%:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                bat 'docker push %IMAGE_NAME%:latest'
            }
        }
    }

    post {
        success {
            echo '✅ Docker Image built and pushed successfully!'
        }
        failure {
            echo '❌ Build failed. Check logs for details.'
        }
    }
}
