pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        IMAGE_NAME = 'venkataramireddy1999/flask-jenkins-docker'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/venkataramireddy1999/jenkins-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    sh 'docker push $IMAGE_NAME:latest'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Docker Image built and pushed successfully!'
        }
        failure {
            echo '❌ Build failed. Check logs for details.'
        }
    }
}
